//
//  CheckViewController.swift
//  HeartsUp
//
//  Created by Elijah Smith on 1/13/17.
//  Copyright © 2017 HeartsUp. All rights reserved.
//

import UIKit
import MessageUI


class CheckViewController: UIViewController, MFMessageComposeViewControllerDelegate {
    
    @IBOutlet weak var buttonDisabled: UIButton!
    let defaults = UserDefaults.standard
    
    //this function needs to change to reflect the model
    func check() {
        let num1 = defaults.double(forKey: "discSwitch1")
        let num2 = defaults.double(forKey: "breathSwitch2")
        let num3 = defaults.double(forKey: "lightSwitch3")
        let num4 = defaults.double(forKey: "numbSwitch4")
        let num5 = defaults.double(forKey: "emotionSwitch5")
        let addition = num1 + num2 + num3 + num4 + num5
        if addition >= 3 {
            buttonDisabled.isEnabled = true
        }
        else {
            buttonDisabled.isEnabled = false
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        check()
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    @IBAction func discSwitch1(_ sender: UISwitch) {
        if sender.isOn == true {
            defaults.set(2, forKey: "discSwitch1")
            print(defaults.string(forKey: "discSwitch1")!)
            check()
        }
        else {
            defaults.set(0, forKey: "discSwitch1")
            print(defaults.string(forKey: "discSwitch1")!)
            check()
        }
    }
    
    @IBAction func breathSwitch2(_ sender: UISwitch) {
        if sender.isOn == true {
            defaults.set(2, forKey: "breathSwitch2")
            check()
        }
        else {
            defaults.set(0, forKey: "breathSwitch2")
            check()
        }
    }
    
    @IBAction func lightSwitch3(_ sender: UISwitch) {
        if sender.isOn == true {
            defaults.set(1, forKey: "lightSwitch3")
            check()
        }
        else {
            defaults.set(0, forKey: "lightSwitch3")
            check()
        }
    }
    
    @IBAction func numbSwitch4(_ sender: UISwitch) {
        if sender.isOn == true {
            defaults.set(1, forKey: "numbSwitch4")
            check()
        }
        else {
            defaults.set(0, forKey: "numbSwitch4")
            check()
        }
    }
    
    @IBAction func emotionSwitch5(_ sender: UISwitch) {
        if sender.isOn == true {
            defaults.set(1, forKey: "emotionSwitch5")
            check()
        }
        else {
            defaults.set(0, forKey: "emotionSwitch5")
            check()
        }
    }
    
    @IBAction func backButton(_ sender: Any) {
        defaults.set(0, forKey: "discSwitch1")
        defaults.set(0, forKey: "breathSwitch2")
        defaults.set(0, forKey: "lightSwitch3")
        defaults.set(0, forKey: "numbSwitch4")
        defaults.set(0, forKey: "emotionSwitch5")
    }
    
    
    @IBAction func textMessageGenerator(_ sender: Any) {
        if (MFMessageComposeViewController.canSendText()) {
            let controller = MFMessageComposeViewController()
            controller.body = "ALERT: I am having a heart attack, please send help! (Message autogenerated by HeartsUp.)"
            controller.recipients = [defaults.string(forKey: "firstEmergencyContact")!, defaults.string(forKey: "secondEmergencyContact")!, defaults.string(forKey: "thirdEmergencyContact")!]
            controller.messageComposeDelegate = self
            self.present(controller, animated: true, completion: nil)
        }
    }
    
    func messageComposeViewController(_ controller: MFMessageComposeViewController, didFinishWith result: MessageComposeResult) {
        self.dismiss(animated: true, completion: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        self.navigationController?.isNavigationBarHidden = true
    }
    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */
}
